"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api, apiForm, ApiError, asList } from "@/lib/api";
import { Card, ErrorBox, PageHeader } from "@/components/ui";
import { Select } from "@/components/ui/Select";

type Step="upload"|"map"|"review"|"complete";
interface ImportRun {id:string;version:number;headers:string[];totalRows:number;validRows?:number;invalidRows?:number;state?:string;errors?:Array<{rowNumber:number;field?:string;message:string}>}
interface Branch {id:string;name:string}
const TARGETS=[{value:"",label:"Do not import"},{value:"names.given",label:"Given name"},{value:"names.middle",label:"Middle name"},{value:"names.family",label:"Family name"},{value:"names.preferred",label:"Preferred name"},{value:"email",label:"Email"},{value:"mobile",label:"Mobile phone"},{value:"whatsapp",label:"WhatsApp"},{value:"dateOfBirth",label:"Date of birth"},{value:"gender",label:"Gender"},{value:"address.line1",label:"Address line"},{value:"address.city",label:"Town or city"},{value:"address.region",label:"Region"},{value:"membershipStage",label:"Membership stage"},{value:"tags",label:"Tags"},{value:"externalId",label:"Legacy external ID"}];

export default function PeopleImportPage(){const [step,setStep]=useState<Step>("upload");const [file,setFile]=useState<File|null>(null);const [branches,setBranches]=useState<Branch[]>([]);const [branchId,setBranchId]=useState("");const [dragging,setDragging]=useState(false);const [run,setRun]=useState<ImportRun|null>(null);const [mapping,setMapping]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{api("/api/branches").then(value=>{const items=asList<Branch>(value);setBranches(items);setBranchId(items[0]?.id||"")}).catch(()=>setBranches([]))},[]);
  async function stage(){if(!file){setError("Choose a CSV file first.");return;}if(!branchId){setError("Choose the branch these people belong to.");return;}setBusy(true);setError(null);try{const form=new FormData();form.append("file",file);form.append("branchId",branchId);form.append("entityType","people");form.append("sourceType","csv");form.append("sourceName",file.name);const created=await apiForm<ImportRun>("/api/chms/v1/imports",form);setRun(created);setMapping(suggestMapping(created.headers));setStep("map");}catch(cause){setError(cause instanceof ApiError?cause.message:"The CSV could not be staged.");}finally{setBusy(false)}}
  async function validate(){if(!run)return;const selected=Object.fromEntries(Object.entries(mapping).filter(([,target])=>target));if(!Object.values(selected).includes("names.given")){setError("Map one source column to Given name.");return;}setBusy(true);setError(null);try{const mapped=await api<ImportRun>(`/api/chms/v1/imports/${run.id}/mapping`,{method:"PUT",body:{expectedVersion:run.version,version:1,fields:selected}});const checked=await api<ImportRun>(`/api/chms/v1/imports/${run.id}/validate`,{method:"POST",body:{expectedVersion:mapped.version}});setRun(checked);setStep("review");}catch(cause){setError(cause instanceof ApiError?cause.message:"The dry run could not be completed.");}finally{setBusy(false)}}
  async function commit(){if(!run)return;setBusy(true);setError(null);try{const completed=await api<ImportRun>(`/api/chms/v1/imports/${run.id}/commit`,{method:"POST",body:{expectedVersion:run.version}});setRun(completed);setStep("complete");}catch(cause){setError(cause instanceof ApiError?cause.message:"The validated rows could not be imported.");}finally{setBusy(false)}}
  return <div><Link href="/people" className="member-back-link">← Back to people</Link><PageHeader title="Import people" subtitle="Stage, map and validate every row before anything enters the member directory."/>
    <ol className="person-import-steps" aria-label="Import progress">{(["upload","map","review","complete"] as Step[]).map((value,index)=><li key={value} aria-current={step===value?"step":undefined} data-complete={index<(["upload","map","review","complete"] as Step[]).indexOf(step)}><span>{String(index+1).padStart(2,"0")}</span><b>{value==="upload"?"Choose file":value==="map"?"Map columns":value==="review"?"Dry run":"Complete"}</b></li>)}</ol>
    {error&&<div className="mb-5"><ErrorBox message={error}/></div>}
    {step==="upload"&&<Card className="person-import-panel"><header className="person-import-head"><div><span>Destination</span><h2>Choose the home branch</h2><p>Every imported person needs an authorized branch scope.</p></div><Select aria-label="Import destination branch" value={branchId} onChange={event=>setBranchId(event.target.value)}><option value="">Choose branch</option>{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></header><div className={`person-import-drop ${dragging?"is-dragging":""}`} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);setFile(event.dataTransfer.files?.[0]||null)}}><span aria-hidden="true">⇧</span><h2>{file?file.name:"Drop a CSV member list here"}</h2><p>{file?`${formatBytes(file.size)} · Ready to stage`:"UTF-8 CSV, maximum 20 MB. Your file is staged before validation."}</p><label><input type="file" accept=".csv,text/csv" onChange={event=>setFile(event.target.files?.[0]||null)}/><b>{file?"Choose another file":"Choose CSV file"}</b></label></div><div className="person-import-guardrails"><div><b>Nothing imports immediately</b><p>Rows stay in staging until mapping and dry-run checks pass.</p></div><div><b>Duplicate files are detected</b><p>Source hashes prevent accidental repeat imports.</p></div><div><b>Rollback manifest retained</b><p>Every committed row keeps provenance for reviewed rollback.</p></div></div><footer><button type="button" disabled={!file||!branchId||busy} onClick={stage} className="admin-primary-button rounded-lg px-5 py-3 text-sm font-semibold">{busy?"Staging…":"Stage CSV"}</button></footer></Card>}
    {step==="map"&&run&&<Card className="person-import-panel"><header className="person-import-head"><div><span>Mapping</span><h2>Match source columns to REMI fields</h2><p>{run.totalRows} rows remain staged. A source column can be skipped.</p></div><button type="button" onClick={()=>setStep("upload")} className="admin-secondary-action rounded-lg px-3 py-2 text-xs">Replace file</button></header><div className="person-mapping-list">{run.headers.map(header=><div key={header}><span><b>{header}</b><small>CSV source column</small></span><span aria-hidden="true">→</span><Select aria-label={`Map ${header}`} value={mapping[header]||""} onChange={event=>setMapping(current=>({...current,[header]:event.target.value}))}>{TARGETS.map(target=><option key={target.value} value={target.value}>{target.label}</option>)}</Select></div>)}</div><footer><button type="button" disabled={busy} onClick={validate} className="admin-primary-button rounded-lg px-5 py-3 text-sm font-semibold">{busy?"Validating…":"Run dry check"}</button></footer></Card>}
    {step==="review"&&run&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><ImportMetric label="Total rows" value={run.totalRows}/><ImportMetric label="Ready" value={run.validRows||0} tone="good"/><ImportMetric label="Needs attention" value={run.invalidRows||0} tone={(run.invalidRows||0)>0?"warn":undefined}/></div><Card className="person-import-panel"><header className="person-import-head"><div><span>Dry-run result</span><h2>Review before commit</h2><p>Only validated rows will be committed. Invalid rows remain staged with their errors.</p></div></header>{run.errors?.length?<div className="person-import-errors"><div><b>Row</b><b>Field</b><b>Issue</b></div>{run.errors.slice(0,50).map((item,index)=><div key={`${item.rowNumber}-${index}`}><span>{item.rowNumber}</span><span>{item.field||"Record"}</span><span>{item.message}</span></div>)}</div>:<p className="person-import-success">All sampled rows passed the current validation rules.</p>}<footer className="!justify-between"><button type="button" onClick={()=>setStep("map")} className="admin-secondary-action rounded-lg px-4 py-3 text-sm font-semibold">Adjust mapping</button><button type="button" disabled={busy||!(run.validRows||0)} onClick={commit} className="admin-primary-button rounded-lg px-5 py-3 text-sm font-semibold">{busy?"Importing…":`Import ${run.validRows||0} valid rows`}</button></footer></Card></div>}
    {step==="complete"&&run&&<Card className="person-import-complete"><span aria-hidden="true">✓</span><h2>People import complete</h2><p>{run.validRows||0} validated rows were committed with their source provenance. Any skipped rows remain available in the import record.</p><div><Link href="/people" className="admin-primary-button rounded-lg px-5 py-3 text-sm font-semibold">Open people directory</Link><Link href={`/people/import/${run.id}`} className="admin-secondary-action rounded-lg px-5 py-3 text-sm font-semibold">View import record</Link></div></Card>}
  </div>;
}
function ImportMetric({label,value,tone}:{label:string;value:number;tone?:"good"|"warn"}){return <Card className="person-import-metric" data-tone={tone}><span>{label}</span><strong>{value}</strong></Card>}
function formatBytes(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1024/1024).toFixed(1)} MB`;}
function suggestMapping(headers:string[]){const aliases:Record<string,string>={firstname:"names.given",givenname:"names.given",surname:"names.family",lastname:"names.family",familyname:"names.family",preferredname:"names.preferred",email:"email",emailaddress:"email",phone:"mobile",mobile:"mobile",phonenumber:"mobile",whatsapp:"whatsapp",dateofbirth:"dateOfBirth",dob:"dateOfBirth",gender:"gender",address:"address.line1",city:"address.city",town:"address.city",region:"address.region",membershipstage:"membershipStage",status:"membershipStage",tags:"tags",externalid:"externalId",memberid:"externalId"};return Object.fromEntries(headers.map(header=>[header,aliases[header.toLowerCase().replace(/[^a-z0-9]/g,"")]||""]));}
