"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { BrandedSelect } from "@/components/branded-select";
import { Icon } from "@/components/icon";

type ResponseState={status:string;version:number};type Meeting={id:string;topic:string;startsAt:string;endsAt:string;timezone:string;location?:string;response?:ResponseState};type Person={id:string;name:string;role?:string;self?:boolean};
export type CommunityData={generatedAt:string;group:{id:string;name:string;type:string;description?:string;meetingPattern?:{frequency:string;weekday:string;localStart:string;location?:string}};membership:{id:string;role:string;status:string;directoryVisibility:string;version:number};meetings:Meeting[];roster:Person[];leaders:Person[];privacy:{version:string;roster:string;responses:string;messages:string}};
export function CommunityWorkspace({initial}:{initial:CommunityData}){const[data,setData]=useState(initial);const[busy,setBusy]=useState("");const[notice,setNotice]=useState("");const[error,setError]=useState("");const[channel,setChannel]=useState("email");const[message,setMessage]=useState("");
async function refresh(){const response=await fetch(`/api/member/community/groups/${data.group.id}/community`,{cache:"no-store"});if(response.ok)setData(await response.json())}
async function respond(meeting:Meeting,status:string){setBusy(meeting.id);setError("");const response=await fetch(`/api/member/community/groups/${data.group.id}/meetings/${meeting.id}/response`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,expectedVersion:meeting.response?.version||0})});const result=await response.json();if(response.ok){setNotice(`Your ${status.replace("-"," ")} response is saved.`);await refresh()}else setError(readError(result,"Your response could not be saved."));setBusy("")}
async function visibility(){setBusy("visibility");setError("");const next=data.membership.directoryVisibility==="members"?"hidden":"members";const response=await fetch(`/api/member/community/groups/${data.group.id}/directory-visibility`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({visibility:next,expectedVersion:data.membership.version})});const result=await response.json();if(response.ok){setNotice(next==="members"?"Your name is now visible to this group.":"Your name is now hidden from the member roster.");await refresh()}else setError(readError(result,"Visibility could not be changed."));setBusy("")}
async function contact(event:FormEvent){event.preventDefault();setBusy("message");setError("");const response=await fetch(`/api/member/community/groups/${data.group.id}/leader-messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel,message})});const result=await response.json();if(response.ok){setMessage("");setNotice("Your message is queued for a consent-safe leader handoff.")}else setError(readError(result,"Your message could not be sent."));setBusy("")}
const future=data.meetings.filter(item=>new Date(item.startsAt)>new Date());return <main className="member-community-page"><header className="member-community-hero"><Link href="/participation#groups"><Icon name="arrow"/>Back to my groups</Link><span>{data.group.type} · MEMBER COMMUNITY</span><h1>{data.group.name}</h1><p>{data.group.description||"A place to connect, grow and participate together."}</p><div><b>{String(data.roster.length).padStart(2,"0")}</b><small>visible people</small><b>{String(future.length).padStart(2,"0")}</b><small>upcoming moments</small></div></header>{error&&<div role="alert" className="member-participation-notice error">{error}</div>}{notice&&<div role="status" className="member-participation-notice">{notice}</div>}
<section className="member-community-calendar"><header><span>01 · CALENDAR</span><h2>Make room for community.</h2><p>{data.privacy.responses}</p></header><div>{future.map(meeting=><article key={meeting.id}><time><b>{new Date(meeting.startsAt).toLocaleDateString("en-GH",{day:"2-digit"})}</b><span>{new Date(meeting.startsAt).toLocaleDateString("en-GH",{month:"short"})}</span></time><div><small>{new Date(meeting.startsAt).toLocaleString("en-GH",{weekday:"long",hour:"numeric",minute:"2-digit"})}</small><h3>{meeting.topic}</h3><p>{meeting.location||"Location will be shared by your leader"}</p></div><fieldset><legend>Your response</legend>{[["going","I’m going"],["maybe","Maybe"],["not-going","Can’t make it"]].map(([value,label])=><button key={value} aria-pressed={meeting.response?.status===value} disabled={busy!==""} onClick={()=>void respond(meeting,value)}>{label}</button>)}</fieldset></article>)}{!future.length&&<div className="member-participation-empty"><strong>No upcoming meetings</strong><p>The next scheduled group moment will appear here.</p></div>}</div></section>
<section className="member-community-people"><header><span>02 · PEOPLE</span><h2>Familiar names,<br/><em>private by choice.</em></h2><p>{data.privacy.roster}</p><button aria-pressed={data.membership.directoryVisibility==="members"} disabled={busy!==""} onClick={()=>void visibility()}><i/><span><b>Show my name to members</b><small>{data.membership.directoryVisibility==="members"?"Visible in this group":"Hidden in this group"}</small></span></button></header><div className="member-community-roster">{data.roster.map((person,index)=><article key={person.id}><i>{person.name.split(" ").map(value=>value[0]).join("").slice(0,2)}</i><div><span>{String(index+1).padStart(2,"0")}</span><h3>{person.name}{person.self&&<small>YOU</small>}</h3><p>{person.role||"member"}</p></div></article>)}</div></section>
<section className="member-community-contact"><div><span>03 · LEADERS</span><h2>A direct line,<br/><em>with boundaries.</em></h2><p>{data.privacy.messages}</p><div>{data.leaders.map(person=><span key={person.id}><i>{person.name.split(" ").map(value=>value[0]).join("").slice(0,2)}</i>{person.name}</span>)}</div></div><form onSubmit={contact}><label><span>Preferred reply channel</span><BrandedSelect value={channel} onChange={event=>setChannel(event.target.value)}><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></BrandedSelect></label><label><span>Your message</span><textarea required minLength={10} maxLength={2000} rows={6} value={message} onChange={event=>setMessage(event.target.value)} placeholder="Share the practical question your leaders can help with…"/></label><button disabled={busy!==""||!data.leaders.length}>{busy==="message"?"Queuing…":"Send to group leaders"}<Icon name="arrow"/></button></form></section><footer className="member-community-policy">{data.privacy.version} · Updated {new Date(data.generatedAt).toLocaleString("en-GH")}</footer></main>}
function readError(value:any,fallback:string){return typeof value?.error==="string"?value.error:typeof value?.error?.message==="string"?value.error.message:fallback}
