"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BrandedSelect } from "@/components/branded-select";

type Group={id:string;name:string};type Membership={id:string;personId:string;status:string;role:string;version:number;directoryVisibility:string;leaderNote?:string};type RosterItem={name:string;membership:Membership};type Meeting={id:string;topic:string;startsAt:string};type Detail={group:Group;roster:RosterItem[];meetings:Meeting[]};type Attendance={personId:string;status:string;version:number};
async function request(path:string,method="GET",body?:unknown){const response=await fetch(path,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.message||data.error?.message||data.error||"The request could not be completed.");return data}

export function LeaderRoster({groups}:{groups:Group[]}){
 const[groupId,setGroupId]=useState(groups[0]?.id||"");const[detail,setDetail]=useState<Detail|null>(null);const[meetingId,setMeetingId]=useState("");const[attendance,setAttendance]=useState<Record<string,Attendance>>({});const[busy,setBusy]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const range=useMemo(()=>{const from=new Date();from.setFullYear(from.getFullYear()-1);const to=new Date();to.setFullYear(to.getFullYear()+1);return`from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`},[]);
 const load=useCallback(async()=>{if(!groupId)return;setError("");try{const value=await request(`/api/member/leader/leader-workspace/groups/${groupId}?${range}`);setDetail(value);setMeetingId(current=>value.meetings.some((item:Meeting)=>item.id===current)?current:value.meetings[0]?.id||"")}catch(cause){setError(cause instanceof Error?cause.message:"Roster could not be loaded.")}},[groupId,range]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!groupId||!meetingId){setAttendance({});return}void request(`/api/member/leader/groups/${groupId}/meetings/${meetingId}/attendance`).then(data=>setAttendance(Object.fromEntries((data.items||[]).map((item:Attendance)=>[item.personId,item])))).catch(cause=>setError(cause instanceof Error?cause.message:"Attendance could not be loaded."))},[groupId,meetingId]);
 async function transition(item:RosterItem,status:string){setBusy(item.membership.id);setError("");try{await request(`/api/member/leader/groups/${groupId}/members/${item.membership.personId}`,"PATCH",{expectedVersion:item.membership.version,status,role:item.membership.role,leaderNote:item.membership.leaderNote||"",directoryVisibility:item.membership.directoryVisibility||"hidden",reason:"Reviewed by group leader"});setNotice(`${item.name} moved to ${status}.`);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Roster update failed.")}finally{setBusy("")}}
 async function mark(item:RosterItem,status:string){const current=attendance[item.membership.personId];setBusy(`attendance-${item.membership.id}`);setError("");try{const value=await request(`/api/member/leader/groups/${groupId}/meetings/${meetingId}/attendance/${item.membership.personId}`,"PUT",{expectedVersion:current?.version||0,status,confidence:100,reason:current?"Leader attendance correction":""});setAttendance(values=>({...values,[item.membership.personId]:value}));setNotice(`${item.name} marked ${status}.`)}catch(cause){setError(cause instanceof Error?cause.message:"Attendance update failed.")}finally{setBusy("")}}
 if(!groups.length)return null;const pending=detail?.roster.filter(item=>["applied","invited","waitlisted"].includes(item.membership.status))||[];const active=detail?.roster.filter(item=>item.membership.status==="active")||[];
 return <section className="member-leader-roster"><header><span>04 · PEOPLE</span><h2>Roster & attendance</h2><p>Only people in the selected owned group appear here. Contact details remain private.</p></header>{error&&<div role="alert" className="member-leader-notice error">{error}</div>}{notice&&<div role="status" className="member-leader-notice">{notice}</div>}<div className="member-leader-roster-controls"><label><span>Group</span><BrandedSelect value={groupId} onChange={event=>setGroupId(event.target.value)}>{groups.map(group=><option value={group.id} key={group.id}>{group.name}</option>)}</BrandedSelect></label><label><span>Meeting</span><BrandedSelect value={meetingId} onChange={event=>setMeetingId(event.target.value)}><option value="">Choose a scheduled meeting</option>{detail?.meetings.map(meeting=><option value={meeting.id} key={meeting.id}>{meeting.topic} · {new Date(meeting.startsAt).toLocaleDateString("en-GH",{day:"numeric",month:"short"})}</option>)}</BrandedSelect></label></div><div className="member-leader-roster-grid"><div><h3>Awaiting review <b>{pending.length}</b></h3>{pending.map(item=><article key={item.membership.id}><div><strong>{item.name}</strong><small>{item.membership.status} · {item.membership.role}</small></div><div><button disabled={busy!==""} onClick={()=>void transition(item,"active")}>Approve</button>{item.membership.status==="applied"&&<button disabled={busy!==""} onClick={()=>void transition(item,"waitlisted")}>Waitlist</button>}</div></article>)}{!pending.length&&<p>No applications, invitations or waitlist entries need review.</p>}</div><div><h3>Meeting attendance <b>{active.length}</b></h3>{!meetingId?<p>Choose a meeting to record attendance.</p>:active.map(item=>{const state=attendance[item.membership.personId]?.status;return <article key={item.membership.id}><div><strong>{item.name}</strong><small>{state||"not recorded"}</small></div><div className="member-attendance-buttons">{["present","absent","excused"].map(status=><button aria-pressed={state===status} disabled={busy!==""} onClick={()=>void mark(item,status)} key={status}>{status}</button>)}</div></article>})}</div></div></section>
}
