"use client";

import { FormEvent, useMemo, useState } from "react";
import { BrandedSelect } from "@/components/branded-select";

type Group = { id: string; name: string };
async function send(path: string, body: unknown) { const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||data.error?.message||data.error||"The request could not be completed.");return data; }

export function LeaderActions({groups}:{groups:Group[]}) {
 const[groupId,setGroupId]=useState(groups[0]?.id||"");const[busy,setBusy]=useState("");const[notice,setNotice]=useState("");const[error,setError]=useState("");
 const[communication,setCommunication]=useState({purpose:"group-operations",channel:"email",message:""});
 const days=useMemo(()=>Array.from({length:60},(_,index)=>{const value=new Date();value.setDate(value.getDate()+index);return{value:value.toISOString().slice(0,10),label:value.toLocaleDateString("en-GH",{weekday:"short",day:"numeric",month:"short"})}}),[]);
 const times=["07:00","08:00","09:00","10:00","12:00","14:00","16:00","17:00","18:00","18:30","19:00","20:00"];
 const[meeting,setMeeting]=useState({topic:"",date:days[0]?.value||"",time:"18:30",duration:"90",location:""});
 async function requestCommunication(event:FormEvent){event.preventDefault();setBusy("message");setError("");setNotice("");try{const value=await send(`/api/member/leader/groups/${groupId}/communication-handoffs`,communication);setCommunication(current=>({...current,message:""}));setNotice(`${value.audiencePersonIds?.length||0} recipients queued for consent and suppression checks.`)}catch(cause){setError(cause instanceof Error?cause.message:"Communication request failed.")}finally{setBusy("")}}
 async function schedule(event:FormEvent){event.preventDefault();setBusy("meeting");setError("");setNotice("");try{const starts=new Date(`${meeting.date}T${meeting.time}:00`);const ends=new Date(starts.getTime()+Number(meeting.duration)*60000);await send(`/api/member/leader/groups/${groupId}/meetings`,{topic:meeting.topic,startsAt:starts.toISOString(),endsAt:ends.toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Africa/Accra",location:meeting.location});setMeeting(current=>({...current,topic:"",location:""}));setNotice("Meeting added to the group schedule.")}catch(cause){setError(cause instanceof Error?cause.message:"Meeting could not be scheduled.")}finally{setBusy("")}}
 if(!groups.length)return null;
 return <section className="member-leader-actions"><header><span>03 · ACTIONS</span><h2>Move the work forward</h2><p>Messages remain pending until current consent, suppressions and verified destinations are checked.</p></header>{error&&<div role="alert" className="member-leader-notice error">{error}</div>}{notice&&<div role="status" className="member-leader-notice">{notice}</div>}<label><span>Working group</span><BrandedSelect value={groupId} onChange={event=>setGroupId(event.target.value)}>{groups.map(group=><option value={group.id} key={group.id}>{group.name}</option>)}</BrandedSelect></label><div className="member-leader-action-grid"><form onSubmit={requestCommunication}><h3>Request a group message</h3><label><span>Purpose</span><BrandedSelect value={communication.purpose} onChange={event=>setCommunication({...communication,purpose:event.target.value})}><option value="group-operations">Group operations</option><option value="church-updates">Church updates</option></BrandedSelect></label><label><span>Preferred channel</span><BrandedSelect value={communication.channel} onChange={event=>setCommunication({...communication,channel:event.target.value})}><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></BrandedSelect></label><label><span>Message</span><textarea required minLength={10} maxLength={2000} rows={5} value={communication.message} onChange={event=>setCommunication({...communication,message:event.target.value})} placeholder="Write the practical update members need…"/></label><button disabled={busy!==""}>{busy==="message"?"Creating handoff…":"Queue consent-aware handoff"}</button></form><form onSubmit={schedule}><h3>Schedule a meeting</h3><label><span>Topic</span><input required minLength={2} value={meeting.topic} onChange={event=>setMeeting({...meeting,topic:event.target.value})}/></label><div className="member-leader-action-row"><label><span>Date</span><BrandedSelect value={meeting.date} onChange={event=>setMeeting({...meeting,date:event.target.value})}>{days.map(day=><option value={day.value} key={day.value}>{day.label}</option>)}</BrandedSelect></label><label><span>Starts</span><BrandedSelect value={meeting.time} onChange={event=>setMeeting({...meeting,time:event.target.value})}>{times.map(time=><option value={time} key={time}>{time}</option>)}</BrandedSelect></label></div><label><span>Duration</span><BrandedSelect value={meeting.duration} onChange={event=>setMeeting({...meeting,duration:event.target.value})}><option value="60">1 hour</option><option value="90">1½ hours</option><option value="120">2 hours</option><option value="150">2½ hours</option></BrandedSelect></label><label><span>Location</span><input value={meeting.location} onChange={event=>setMeeting({...meeting,location:event.target.value})} placeholder="Fellowship hall"/></label><button disabled={busy!==""}>{busy==="meeting"?"Scheduling…":"Add to group schedule"}</button></form></div></section>;
}
