"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { BrandedSelect } from "@/components/branded-select";
import { Icon } from "@/components/icon";

type InboxItem = { id: string; subject: string; preview: string; purpose: string; channel: string; state: string; sentAt: string; readAt?: string };
type Group = { id: string; name: string; canMessage: boolean };
type Preferences = { quietEnabled: boolean; quietStart: string; quietEnd: string; timezone: string; dailyCap: number; directoryFields: string[]; version: number };
type DirectoryPerson = { id: string; name: string; self?: boolean; contacts?: { email?: string; mobile?: string } };
type GroupMessage = { id: string; author: string; message: string; createdAt: string; self?: boolean };
export type CommunicationWorkspace = { preferences: Preferences; inbox: InboxItem[]; groups: Group[]; unreadCount: number };

const TIMES = Array.from({ length: 48 }, (_, index) => { const hour = Math.floor(index / 2); const minute = index % 2 ? "30" : "00"; const value = `${String(hour).padStart(2, "0")}:${minute}`; return { value, label: new Date(`2000-01-01T${value}:00`).toLocaleTimeString("en-GH", { hour: "numeric", minute: "2-digit" }) }; });
const tabs = ["inbox", "directory", "groups", "preferences"] as const;
type Tab = typeof tabs[number];

async function json(response: Response) { const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || "That could not be completed."); return payload; }
const when = (value: string) => new Intl.DateTimeFormat("en-GH", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }).format(new Date(value));

export function MessagesWorkspace({ initial }: { initial: CommunicationWorkspace | null }) {
  const [data, setData] = useState(initial);
  const [tab, setTab] = useState<Tab>("inbox");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState(initial ? "" : "Messages are temporarily unavailable.");
  const [busy, setBusy] = useState("");
  const [scope, setScope] = useState<"branch" | "group">("branch");
  const [groupId, setGroupId] = useState(initial?.groups[0]?.id || "");
  const [query, setQuery] = useState("");
  const [directory, setDirectory] = useState<DirectoryPerson[]>([]);
  const [messages, setMessages] = useState<GroupMessage[]>([]);
  const [draft, setDraft] = useState("");
  const [preferences, setPreferences] = useState<Preferences>(initial?.preferences || { quietEnabled: true, quietStart: "21:00", quietEnd: "07:00", timezone: "Africa/Accra", dailyCap: 3, directoryFields: [], version: 0 });
  const selectedGroup = data?.groups.find(group => group.id === groupId);
  const visibleInbox = useMemo(() => data?.inbox || [], [data]);

  async function refresh() { const next = await json(await fetch("/api/member/messages/workspace")); setData(next); setPreferences(next.preferences); }
  async function inboxAction(id: string, action: "read" | "unread" | "archive") { setBusy(id); setError(""); try { await json(await fetch(`/api/member/messages/inbox/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) })); await refresh(); } catch (value) { setError(value instanceof Error ? value.message : "Message could not be updated."); } finally { setBusy(""); } }
  async function loadDirectory() { setBusy("directory"); setError(""); try { const params = new URLSearchParams({ scope, q: query }); if (scope === "group") params.set("groupId", groupId); const result = await json(await fetch(`/api/member/messages/directory?${params}`)); setDirectory(result.items || []); } catch (value) { setError(value instanceof Error ? value.message : "Directory unavailable."); setDirectory([]); } finally { setBusy(""); } }
  async function loadMessages(nextGroup = groupId) { if (!nextGroup) return; setBusy("messages"); setError(""); try { const result = await json(await fetch(`/api/member/messages/groups/${nextGroup}/messages`)); setMessages(result.items || []); } catch (value) { setError(value instanceof Error ? value.message : "Conversation unavailable."); } finally { setBusy(""); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!groupId || !draft.trim()) return; setBusy("send"); setError(""); try { await json(await fetch(`/api/member/messages/groups/${groupId}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: draft }) })); setDraft(""); await loadMessages(); } catch (value) { setError(value instanceof Error ? value.message : "Message could not be sent."); } finally { setBusy(""); } }
  async function savePreferences() { setBusy("preferences"); setError(""); setNotice(""); try { const next = await json(await fetch("/api/member/messages/preferences", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...preferences, expectedVersion: preferences.version }) })); setPreferences(next); setNotice("Communication preferences saved."); } catch (value) { setError(value instanceof Error ? value.message : "Preferences could not be saved."); } finally { setBusy(""); } }
  function toggleField(field: string) { setPreferences(current => ({ ...current, directoryFields: current.directoryFields.includes(field) ? current.directoryFields.filter(value => value !== field) : [...current.directoryFields, field] })); }

  useEffect(() => { if (tab === "directory") void loadDirectory(); }, [tab, scope, groupId]);
  useEffect(() => { if (tab === "groups") void loadMessages(); }, [tab, groupId]);

  return <main className="member-messages-page">
    <header className="member-messages-hero"><div><span>STAY CONNECTED</span><h1>Your conversations,<br/><em>kept thoughtful.</em></h1><p>Church updates, people you choose to find, and group conversations—without the noise.</p></div><aside><b>{String(data?.unreadCount || 0).padStart(2, "0")}</b><span>unread messages</span><i><Icon name="bell"/></i></aside></header>
    <nav className="member-messages-tabs" aria-label="Messages sections">{tabs.map(value => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}><i/>{value}</button>)}</nav>
    {error && <div className="member-message-notice error" role="alert">{error}</div>}{notice && <div className="member-message-notice" role="status">{notice}</div>}

    {tab === "inbox" && <section className="member-inbox"><header><div><span>01 · INBOX</span><h2>News meant for you.</h2></div><p>Only communications actually accepted for your account appear here. Provider status remains separate.</p></header><div>{visibleInbox.map(item => <article className={item.readAt ? "read" : ""} key={item.id}><i/><div><span>{item.purpose.replaceAll("-", " ")} · {item.channel}</span><h3>{item.subject}</h3><p>{item.preview}</p><small>{when(item.sentAt)}</small></div><footer>{item.readAt ? <button disabled={busy === item.id} onClick={() => void inboxAction(item.id, "unread")}>Mark unread</button> : <button disabled={busy === item.id} onClick={() => void inboxAction(item.id, "read")}>Mark read</button>}<button disabled={busy === item.id} onClick={() => void inboxAction(item.id, "archive")}>Archive</button></footer></article>)}{!visibleInbox.length && <div className="member-message-empty"><Icon name="bell"/><b>Your inbox is clear.</b><p>Updates sent with your current consent will appear here.</p></div>}</div></section>}

    {tab === "directory" && <section className="member-directory"><header><div><span>02 · DIRECTORY</span><h2>Find your church people.</h2><p>This is not a church-wide contact book. Minors and private profiles never appear.</p></div><div><BrandedSelect aria-label="Directory scope" value={scope} onChange={event => setScope(event.target.value as "branch"|"group")}><option value="branch">My branch</option><option value="group">One of my groups</option></BrandedSelect>{scope === "group" && <BrandedSelect aria-label="Group" value={groupId} onChange={event => setGroupId(event.target.value)}>{data?.groups.map(group => <option value={group.id} key={group.id}>{group.name}</option>)}</BrandedSelect>}</div></header><form onSubmit={event => { event.preventDefault(); void loadDirectory(); }}><input value={query} maxLength={80} onChange={event => setQuery(event.target.value)} placeholder="Search by name"/><button disabled={busy === "directory"}>Search</button></form><div className="member-directory-grid">{directory.map(person => <article key={person.id}><i>{person.name.split(/\s+/).map(value => value[0]).join("").slice(0,2)}</i><div><b>{person.name}{person.self ? " · You" : ""}</b><span>{person.contacts?.email || person.contacts?.mobile || "Name shared only"}</span></div></article>)}{busy !== "directory" && !directory.length && <div className="member-message-empty"><Icon name="users"/><b>No shared profiles found.</b><p>Try another name or choose a shared group.</p></div>}</div></section>}

    {tab === "groups" && <section className="member-group-chat"><header><div><span>03 · GROUP CONVERSATIONS</span><h2>Keep the circle close.</h2></div><BrandedSelect aria-label="Conversation group" value={groupId} onChange={event => { setGroupId(event.target.value); void loadMessages(event.target.value); }}>{data?.groups.map(group => <option value={group.id} key={group.id}>{group.name}</option>)}</BrandedSelect></header><div className="member-chat-stream">{messages.map(message => <article className={message.self ? "self" : ""} key={message.id}><span>{message.author}</span><p>{message.message}</p><small>{when(message.createdAt)}</small></article>)}{!messages.length && <div className="member-message-empty"><Icon name="users"/><b>No messages yet.</b><p>Start a practical conversation with this group.</p></div>}</div><form onSubmit={send}><textarea aria-label="Group message" rows={3} minLength={2} maxLength={1200} value={draft} onChange={event => setDraft(event.target.value)} placeholder={selectedGroup?.canMessage ? "Write to your group…" : "Make your name visible to this group before posting."} disabled={!selectedGroup?.canMessage}/><div><small>{draft.length}/1200 · visible to active adult members</small><button disabled={busy === "send" || !selectedGroup?.canMessage || draft.trim().length < 2}>Send <Icon name="arrow"/></button></div></form></section>}

    {tab === "preferences" && <section className="member-message-preferences"><header><span>04 · YOUR PACE</span><h2>Set a quieter rhythm.</h2><p>These limits narrow non-essential campaign messages. Security and transactional notices still arrive when needed.</p></header><div className="member-preference-canvas"><button className={`member-quiet-toggle ${preferences.quietEnabled ? "active" : ""}`} aria-pressed={preferences.quietEnabled} onClick={() => setPreferences(current => ({ ...current, quietEnabled: !current.quietEnabled }))}><i><span/></i><div><b>Quiet hours</b><small>Pause campaign delivery during your rest window.</small></div></button><div className="member-time-pair"><label><span>From</span><BrandedSelect value={preferences.quietStart} onChange={event => setPreferences(current => ({ ...current, quietStart: event.target.value }))}>{TIMES.map(time => <option value={time.value} key={time.value}>{time.label}</option>)}</BrandedSelect></label><label><span>Until</span><BrandedSelect value={preferences.quietEnd} onChange={event => setPreferences(current => ({ ...current, quietEnd: event.target.value }))}>{TIMES.map(time => <option value={time.value} key={time.value}>{time.label}</option>)}</BrandedSelect></label></div><fieldset><legend>Daily campaign limit</legend><div>{[1,2,3,4,5].map(cap => <button type="button" aria-pressed={preferences.dailyCap === cap} onClick={() => setPreferences(current => ({ ...current, dailyCap: cap }))} key={cap}><b>{cap}</b><span>{cap === 1 ? "message" : "messages"}</span></button>)}</div></fieldset><fieldset><legend>Details I share in the directory</legend><div className="member-directory-field-choices">{[["email","Email address"],["mobile","Mobile number"]].map(([field,label]) => <button type="button" aria-pressed={preferences.directoryFields.includes(field)} onClick={() => toggleField(field)} key={field}><i>{preferences.directoryFields.includes(field) ? "✓" : "+"}</i><span><b>{label}</b><small>Your name may still appear where your profile visibility allows it.</small></span></button>)}</div></fieldset><a href="/account?tab=privacy">Manage channel consent for email, SMS, WhatsApp and push <Icon name="arrow"/></a><button className="member-save-message-preferences" disabled={busy === "preferences"} onClick={() => void savePreferences()}>{busy === "preferences" ? "Saving…" : "Save my rhythm"}</button></div></section>}
  </main>;
}
