"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { api, ApiError, asList } from "@/lib/api";
import { Card, EmptyState, ErrorBox, PageHeader } from "@/components/ui";
import { Select } from "@/components/ui/Select";

type Branch = { id: string; name: string };
type GroupRow = { groupId: string; name: string; type: string; status: string; capacity: number; currentActiveMembers: number; pendingMembers: number; currentCapacityPercent?: number; meetingsHeld: number; recordedPresent: number; recordedAbsentOrExcused: number; recordedAttendanceRate?: number; suppressed: boolean };
type TeamRow = { teamId: string; name: string; status: string; activePositions: number; plannedSlots: number; filledSlots: number; uniqueScheduledVolunteers: number; invited: number; accepted: number; declined: number; completed: number; noShows: number; fillRate?: number; responseRate?: number; noShowRate?: number; suppressed: boolean };
type Dashboard = { range: { branchId: string; from: string; to: string }; summary: { activeGroups: number; activeGroupMemberships: number; uniqueConnectedPeople: number; meetingsHeld: number; activeVolunteerTeams: number; uniqueScheduledVolunteers: number; plannedServingSlots: number; filledServingSlots: number }; groups: GroupRow[]; volunteerTeams: TeamRow[]; quality: { groupsWithoutCapacity: number; meetingsWithoutMarks: number; plansWithoutNeeds: number; assignmentsWithoutTeamMatch: number; latestRecordedAt?: string; caveats: string[] }; privacyThreshold: number; metricVersion: string; generatedAt: string };

const WINDOWS = [{ days: 30, label: "30 days" }, { days: 90, label: "90 days" }, { days: 180, label: "6 months" }, { days: 365, label: "12 months" }];
const pct = (value?: number) => value == null ? "—" : `${value}%`;

export default function MinistryInsightsPage() {
  const [branches, setBranches] = useState<Branch[]>([]); const [branchId, setBranchId] = useState(""); const [days, setDays] = useState(90); const [data, setData] = useState<Dashboard | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { api("/api/branches").then(value => { const items = asList<Branch>(value); setBranches(items); setBranchId(items[0]?.id || ""); }).catch(() => setError("Branches could not be loaded.")); }, []);
  const range = useMemo(() => { const to = new Date(); const from = new Date(to); from.setUTCDate(from.getUTCDate() - days); return { from: from.toISOString(), to: to.toISOString() }; }, [days]);
  const load = useCallback(async () => { if (!branchId) { setLoading(false); return; } setLoading(true); setError(null); try { setData(await api<Dashboard>(`/api/chms/v1/community-analytics?branchId=${encodeURIComponent(branchId)}&from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}`)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Ministry insights could not be loaded."); } finally { setLoading(false); } }, [branchId, range]);
  useEffect(() => { void load(); }, [load]);
  return <div className="ministry-insights"><PageHeader title="Ministry insights" subtitle="Auditable group health and serving readiness—without turning people into scores."><Link href="/groups" className="admin-secondary-action rounded-lg px-4 py-2.5 text-sm font-semibold">← Groups</Link><Select aria-label="Branch" value={branchId} onChange={event => setBranchId(event.target.value)}><option value="">Choose branch</option>{branches.map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></PageHeader>
    <section className="insights-range" aria-label="Reporting range"><span>Observation window</span><div>{WINDOWS.map(window => <button type="button" key={window.days} aria-pressed={days === window.days} onClick={() => setDays(window.days)}>{window.label}</button>)}</div>{data && <small>As of {new Date(data.generatedAt).toLocaleString()} · {data.metricVersion}</small>}</section>
    {error && <div className="mb-5"><ErrorBox message={error} onRetry={load}/></div>}{loading ? <InsightsSkeleton /> : !data ? <EmptyState title="Choose a branch" hint="Analytics are always authorized and calculated within one branch." /> : <>
      <section className="insights-metrics">{[
        ["01", data.summary.uniqueConnectedPeople, "Connected people", `${data.summary.activeGroupMemberships} active memberships`],
        ["02", data.summary.activeGroups, "Active groups", `${data.summary.meetingsHeld} meetings held`],
        ["03", data.summary.uniqueScheduledVolunteers, "Scheduled volunteers", `${data.summary.activeVolunteerTeams} active teams`],
        ["04", `${data.summary.filledServingSlots}/${data.summary.plannedServingSlots}`, "Filled serving slots", "From configured plan needs"],
      ].map(([index, value, label, note]) => <article key={String(index)}><span>{index}</span><b>{value}</b><h2>{label}</h2><p>{note}</p></article>)}</section>
      <section className="insights-grid"><Card className="insights-panel"><header><div><span>GROUPS · CURRENT + RANGE</span><h2>Community health</h2></div><p>Capacity is current. Meeting activity belongs to the selected window.</p></header>{data.groups.length ? <div className="insights-rows">{data.groups.map(group => <article key={group.groupId}><div className="insights-row-title"><div><strong>{group.name}</strong><small>{group.type} · {group.status}</small></div><Link href={`/groups/${group.groupId}`}>View →</Link></div><div className="insights-bars"><MetricBar label="Current capacity" value={group.currentCapacityPercent} copy={`${group.currentActiveMembers}/${group.capacity || "open"}`} /><MetricBar label="Recorded attendance" value={group.recordedAttendanceRate} copy={group.suppressed ? `< ${data.privacyThreshold} marks · suppressed` : `${group.recordedPresent}/${group.recordedPresent + group.recordedAbsentOrExcused} explicit marks`} /></div><footer><span>{group.meetingsHeld} meetings</span><span>{group.pendingMembers} awaiting review</span></footer></article>)}</div> : <EmptyState dense title="No configured groups" hint="Create a group to begin observing ministry operations." />}</Card>
      <Card className="insights-panel"><header><div><span>VOLUNTEERS · RANGE</span><h2>Serving readiness</h2></div><p>Fill comes from plan needs; responses and outcomes come from assignments.</p></header>{data.volunteerTeams.length ? <div className="insights-rows">{data.volunteerTeams.map(team => <article key={team.teamId}><div className="insights-row-title"><div><strong>{team.name}</strong><small>{team.activePositions} positions · {team.uniqueScheduledVolunteers} people</small></div><Link href="/volunteers/schedule">Schedule →</Link></div><div className="insights-team-rates"><Rate label="Fill" value={team.fillRate} /><Rate label="Response" value={team.responseRate} /><Rate label="No-show" value={team.noShowRate} inverse /></div><footer><span>{team.filledSlots}/{team.plannedSlots} slots</span><span>{team.completed} completed · {team.noShows} no-show</span>{team.suppressed && <span>small rates suppressed</span>}</footer></article>)}</div> : <EmptyState dense title="No volunteer teams" hint="Create teams and service plans to measure serving readiness." />}</Card></section>
      <Card className="insights-quality"><header><span>DATA QUALITY · READ BEFORE INTERPRETING</span><h2>Coverage and caveats</h2></header><div className="insights-quality-counts"><Quality value={data.quality.meetingsWithoutMarks} label="meetings without marks" /><Quality value={data.quality.groupsWithoutCapacity} label="groups without capacity" /><Quality value={data.quality.plansWithoutNeeds} label="plans without needs" /><Quality value={data.quality.assignmentsWithoutTeamMatch} label="unmatched assignments" /></div><ol>{data.quality.caveats.map((caveat, index) => <li key={caveat}><b>{String(index + 1).padStart(2, "0")}</b><span>{caveat}</span></li>)}</ol><footer>Latest source change: {data.quality.latestRecordedAt ? new Date(data.quality.latestRecordedAt).toLocaleString() : "No recorded activity in range"} · Rates return no value when observations or distinct people fall below {data.privacyThreshold}.</footer></Card>
    </>}</div>;
}

function MetricBar({ label, value, copy }: { label: string; value?: number; copy: string }) { return <div><span><b>{label}</b><em>{pct(value)}</em></span><i><span style={{ width: `${value || 0}%` }} /></i><small>{copy}</small></div>; }
function Rate({ label, value, inverse = false }: { label: string; value?: number; inverse?: boolean }) { return <div style={{ "--rate": `${value || 0}%` } as React.CSSProperties} className={inverse ? "inverse" : ""}><i><b>{pct(value)}</b></i><span>{label}</span></div>; }
function Quality({ value, label }: { value: number; label: string }) { return <div><b>{String(value).padStart(2, "0")}</b><span>{label}</span></div>; }
function InsightsSkeleton() { return <div className="insights-skeleton" aria-label="Loading ministry insights">{Array.from({ length: 8 }, (_, index) => <i key={index} />)}</div>; }
