"use client";

import { useEffect, useId, useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { api, ApiError, asList } from "@/lib/api";
import type { MemberProfile } from "@/lib/chms";
import { Card, ErrorBox } from "@/components/ui";
import { Select } from "@/components/ui/Select";

const GHANA_REGIONS = ["Ahafo","Ashanti","Bono","Bono East","Central","Eastern","Greater Accra","North East","Northern","Oti","Savannah","Upper East","Upper West","Volta","Western","Western North"];
const STAGES = ["guest","returning-guest","regular-attendee","member","inactive","transferred","deceased"];
const COMMON_TAGS = ["choir","children","first-time-guest","follow-up","intercession","member-class","new-believer","volunteer","youth"];
type ContactType = "email"|"mobile"|"whatsapp"|"phone";
interface Branch { id:string;name:string }
interface ContactDraft { id:string;type:ContactType;value:string;primary:boolean }
interface FormState {
  names:{given:string;middle:string;family:string;preferred:string}; photoAssetId:string; photoPreviewUrl:string; dateOfBirth:{value:string;precision:"year"|"month"|"day"}|null; gender:string;
  homeBranchId:string; membershipStage:string; contacts:ContactDraft[]; address:{line1:string;line2:string;city:string;region:string;country:string}; tags:string[];
  preferences:{email:boolean;sms:boolean;whatsapp:boolean;phone:boolean}; source:{type:string;reference:string;noticeVersion:string};
}

const EMPTY:FormState={names:{given:"",middle:"",family:"",preferred:""},photoAssetId:"",photoPreviewUrl:"",dateOfBirth:null,gender:"",homeBranchId:"",membershipStage:"guest",contacts:[{id:"contact-1",type:"mobile",value:"",primary:true}],address:{line1:"",line2:"",city:"",region:"Greater Accra",country:"GH"},tags:[],preferences:{email:false,sms:false,whatsapp:false,phone:false},source:{type:"staff-entry",reference:"",noticeVersion:"2026-01"}};

export function PersonForm({mode,person}:{mode:"create"|"edit";person?:MemberProfile["person"]}) {
  const router=useRouter(); const formId=useId(); const draftKey=`remi-person-${mode}-${person?.id||"new"}`;
  const [form,setForm]=useState<FormState>(()=>person?fromPerson(person):EMPTY); const [branches,setBranches]=useState<Branch[]>([]); const [tagInput,setTagInput]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [draftNotice,setDraftNotice]=useState(false); const [savedAt,setSavedAt]=useState<Date|null>(null);
  const [showErrors,setShowErrors]=useState(false);
  const [uploading,setUploading]=useState(false); const [dragging,setDragging]=useState(false);

  useEffect(()=>{api("/api/branches").then(value=>{const items=asList<Branch>(value);setBranches(items);setForm(current=>({...current,homeBranchId:current.homeBranchId||items[0]?.id||""}));}).catch(()=>setBranches([]));},[]);
  useEffect(()=>{if(person)return;try{const raw=localStorage.getItem(draftKey);if(raw){const recovered=JSON.parse(raw) as FormState;if(hasMeaningfulDraft(recovered)){setForm(recovered);setDraftNotice(true);}else localStorage.removeItem(draftKey);}}catch{}},[draftKey,person]);
  useEffect(()=>{const timer=window.setTimeout(()=>{try{if(mode==="create"&&!hasMeaningfulDraft(form)){localStorage.removeItem(draftKey);setSavedAt(null);return;}localStorage.setItem(draftKey,JSON.stringify(form));setSavedAt(new Date());}catch{}},500);return()=>window.clearTimeout(timer);},[draftKey,form,mode]);
  const errors=useMemo(()=>validate(form),[form]);
  const visibleErrors=showErrors?errors:{};

  function patch<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>({...current,[key]:value}));}
  function patchName(key:keyof FormState["names"],value:string){setForm(current=>({...current,names:{...current.names,[key]:value}}));}
  function patchAddress(key:keyof FormState["address"],value:string){setForm(current=>({...current,address:{...current.address,[key]:value}}));}
  function patchContact(id:string,values:Partial<ContactDraft>){setForm(current=>{const selected=current.contacts.find(contact=>contact.id===id);const nextType=values.type||selected?.type;const shouldOwnPrimary=values.primary===true||(Boolean(values.type)&&selected?.primary===true);return {...current,contacts:current.contacts.map(contact=>contact.id===id?{...contact,...values}:shouldOwnPrimary&&contact.type===nextType?{...contact,primary:false}:contact)};});}
  function addContact(){setForm(current=>({...current,contacts:[...current.contacts,{id:crypto.randomUUID(),type:"mobile",value:"",primary:false}]}));}
  function removeContact(id:string){setForm(current=>({...current,contacts:current.contacts.filter(contact=>contact.id!==id)}));}
  function addTag(value=tagInput){const normalized=value.trim().toLowerCase();if(!normalized||form.tags.includes(normalized))return;patch("tags",[...form.tags,normalized]);setTagInput("");}
  function discardDraft(){localStorage.removeItem(draftKey);setForm(person?fromPerson(person):EMPTY);setDraftNotice(false);}

  async function upload(file?:File){if(!file)return;if(!file.type.startsWith("image/")||file.size>10*1024*1024){setError("Choose a JPG, PNG, WebP or AVIF image up to 10 MB.");return;}setUploading(true);setError(null);try{const signed=await api<{cloudName:string;apiKey:string;timestamp:number;signature:string;folder:string}>("/api/admin/uploads/signature",{method:"POST",body:{folder:"remi/people"}});const data=new FormData();data.append("file",file);data.append("api_key",signed.apiKey);data.append("timestamp",String(signed.timestamp));data.append("signature",signed.signature);data.append("folder",signed.folder);const response=await fetch(`https://api.cloudinary.com/v1_1/${signed.cloudName}/image/upload`,{method:"POST",body:data});const result=await response.json() as {secure_url?:string;public_id?:string;error?:{message?:string}};if(!response.ok||!result.secure_url||!result.public_id)throw new Error(result.error?.message||"Image upload failed.");setForm(current=>({...current,photoAssetId:result.public_id!,photoPreviewUrl:result.secure_url!}));}catch(cause){setError(cause instanceof Error?cause.message:"Image upload failed.");}finally{setUploading(false);}}

  async function submit(event:FormEvent){event.preventDefault();setShowErrors(true);if(Object.keys(errors).length){setError("Check the highlighted fields before saving.");document.getElementById(Object.keys(errors)[0])?.focus();return;}setBusy(true);setError(null);try{const body=toPayload(form);const response=mode==="create"?await api<{id:string}>("/api/chms/v1/people",{method:"POST",body}):await api<{id:string}>(`/api/chms/v1/people/${person!.id}`,{method:"PATCH",body:{...body,expectedVersion:person!.version}});localStorage.removeItem(draftKey);router.push(`/people/${response.id||person?.id}`);}catch(cause){setError(cause instanceof ApiError?cause.message:"The person could not be saved.");}finally{setBusy(false);}}

  return <form id={formId} onSubmit={submit} noValidate className="space-y-5">
    {draftNotice&&<div className="person-draft-banner" role="status"><span><b>Draft restored</b><small>Your unfinished entry was recovered from this browser.</small></span><button type="button" onClick={discardDraft}>Discard draft</button></div>}
    {error&&<ErrorBox message={error}/>} 
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_19rem]">
      <div className="space-y-5">
        <FormPanel index="01" title="Identity" note="Use the person’s own name and only the detail needed for ministry care.">
          <div className="grid gap-4 sm:grid-cols-2"><Field id="given" label="Given name" required error={visibleErrors.given}><input id="given" value={form.names.given} onChange={event=>patchName("given",event.target.value)} autoComplete="given-name"/></Field><Field id="family" label="Family name" error={visibleErrors.family}><input id="family" value={form.names.family} onChange={event=>patchName("family",event.target.value)} autoComplete="family-name"/></Field><Field id="middle" label="Middle name"><input id="middle" value={form.names.middle} onChange={event=>patchName("middle",event.target.value)} autoComplete="additional-name"/></Field><Field id="preferred" label="Preferred name" hint="Shown in everyday ministry communication."><input id="preferred" value={form.names.preferred} onChange={event=>patchName("preferred",event.target.value)}/></Field></div>
          <div className="mt-4 grid gap-4 sm:grid-cols-3"><Field id="dob-precision" label="Birth date precision"><Select id="dob-precision" value={form.dateOfBirth?.precision||""} onChange={event=>patch("dateOfBirth",event.target.value?{precision:event.target.value as "year"|"month"|"day",value:""}:null)}><option value="">Not recorded</option><option value="year">Year only</option><option value="month">Month and year</option><option value="day">Exact date</option></Select></Field>{form.dateOfBirth&&<Field id="dob" label="Birth date" error={visibleErrors.dob}><input id="dob" type={form.dateOfBirth.precision==="day"?"date":form.dateOfBirth.precision==="month"?"month":"number"} min={form.dateOfBirth.precision==="year"?"1900":undefined} max={form.dateOfBirth.precision==="year"?String(new Date().getFullYear()):undefined} value={form.dateOfBirth.value} onChange={event=>patch("dateOfBirth",{...form.dateOfBirth!,value:event.target.value})}/></Field>}<Field id="gender" label="Gender" hint="Optional and self-described."><Select id="gender" value={form.gender} onChange={event=>patch("gender",event.target.value)}><option value="">Prefer not to record</option><option value="female">Female</option><option value="male">Male</option><option value="non-binary">Non-binary</option><option value="self-described">Self-described</option></Select></Field></div>
        </FormPanel>
        <FormPanel index="02" title="Contact channels" note="Ghana phone numbers are normalized to +233; choose one primary per channel.">
          <div className="space-y-3">{form.contacts.map((contact,index)=><div className="person-contact-row" key={contact.id}><Field id={`contact-type-${contact.id}`} label={index===0?"Type":"Contact type"}><Select id={`contact-type-${contact.id}`} value={contact.type} onChange={event=>patchContact(contact.id,{type:event.target.value as ContactType})}><option value="mobile">Mobile</option><option value="whatsapp">WhatsApp</option><option value="phone">Other phone</option><option value="email">Email</option></Select></Field><Field id={`contact-${contact.id}`} label={index===0?"Contact":"Value"} error={visibleErrors[`contact-${contact.id}`]}><input id={`contact-${contact.id}`} type={contact.type==="email"?"email":"tel"} inputMode={contact.type==="email"?"email":"tel"} placeholder={contact.type==="email"?"name@example.com":"024 000 0000"} value={contact.value} onChange={event=>patchContact(contact.id,{value:event.target.value})}/></Field><label className="person-primary-choice"><input type="radio" name={`primary-${contact.type}`} checked={contact.primary} onChange={()=>patchContact(contact.id,{primary:true})}/><span>Primary</span></label><button type="button" className="admin-danger-button rounded-lg px-3 py-2 text-xs" onClick={()=>removeContact(contact.id)} disabled={form.contacts.length===1}>Remove</button></div>)}</div><button type="button" onClick={addContact} className="admin-secondary-action mt-4 rounded-lg px-4 py-2 text-sm font-semibold">Add contact</button>
        </FormPanel>
        <FormPanel index="03" title="Address" note="Region is selected from Ghana’s administrative regions to keep reports consistent.">
          <div className="grid gap-4 sm:grid-cols-2"><Field id="line1" label="Address line" error={visibleErrors.line1}><input id="line1" value={form.address.line1} onChange={event=>patchAddress("line1",event.target.value)} autoComplete="address-line1"/></Field><Field id="line2" label="Additional detail"><input id="line2" value={form.address.line2} onChange={event=>patchAddress("line2",event.target.value)} autoComplete="address-line2"/></Field><Field id="region" label="Region"><Select id="region" value={form.address.region} onChange={event=>patchAddress("region",event.target.value)}>{GHANA_REGIONS.map(region=><option key={region} value={region}>{region}</option>)}</Select></Field><Field id="city" label="Town or city"><input id="city" value={form.address.city} onChange={event=>patchAddress("city",event.target.value)} autoComplete="address-level2"/></Field></div>
        </FormPanel>
      </div>
      <aside className="space-y-5 xl:sticky xl:top-24">
        <FormPanel index="04" title="Ministry context" note="Branch and stage drive access and follow-up workflows."><div className="space-y-4"><Field id="branch" label="Home branch" required error={visibleErrors.branch}><Select id="branch" value={form.homeBranchId} onChange={event=>patch("homeBranchId",event.target.value)}><option value="">Choose a branch</option>{branches.map(branch=><option key={branch.id} value={branch.id}>{branch.name}</option>)}</Select></Field><Field id="stage" label="Membership stage"><Select id="stage" value={form.membershipStage} onChange={event=>patch("membershipStage",event.target.value)}>{STAGES.map(stage=><option key={stage} value={stage}>{stage.replaceAll("-"," ")}</option>)}</Select></Field></div></FormPanel>
        <FormPanel index="05" title="Profile image" note="JPG, PNG, WebP or AVIF. Maximum 10 MB."><div className={`person-photo-drop ${dragging?"is-dragging":""}`} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);upload(event.dataTransfer.files?.[0])}}>{form.photoPreviewUrl?<img src={form.photoPreviewUrl} alt="Profile preview"/>:<span aria-hidden="true">◎</span>}<label><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={event=>upload(event.target.files?.[0])}/><b>{uploading?"Uploading…":form.photoAssetId?"Replace image":"Upload image"}</b><small>or drag and drop</small></label></div></FormPanel>
        <FormPanel index="06" title="Tags" note="Choose common tags or add a concise operational label."><div className="flex flex-wrap gap-2">{form.tags.map(tag=><button type="button" key={tag} className="member-tag" onClick={()=>patch("tags",form.tags.filter(value=>value!==tag))}>{tag} ×</button>)}</div><div className="mt-3 flex gap-2"><input list="person-tag-suggestions" value={tagInput} onChange={event=>setTagInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();addTag()}}} placeholder="Add tag" aria-label="Add tag"/><datalist id="person-tag-suggestions">{COMMON_TAGS.filter(tag=>!form.tags.includes(tag)).map(tag=><option key={tag} value={tag}/>)}</datalist><button type="button" className="admin-secondary-action rounded-lg px-3 text-sm" onClick={()=>addTag()}>Add</button></div></FormPanel>
        <Card className="person-form-submit"><div><b>{savedAt?`Draft saved ${savedAt.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:"Draft protection active"}</b><small>Saved only in this browser until submitted.</small></div><button type="submit" className="admin-primary-button rounded-lg px-5 py-3 text-sm font-semibold" disabled={busy||uploading}>{busy?"Saving…":mode==="create"?"Create person":"Save changes"}</button></Card>
      </aside>
    </div>
  </form>;
}

function FormPanel({index,title,note,children}:{index:string;title:string;note:string;children:React.ReactNode}){return <Card className="person-form-panel"><header><span>{index}</span><div><h2>{title}</h2><p>{note}</p></div></header><div className="person-form-panel-body">{children}</div></Card>}
function Field({id,label,hint,error,required,children}:{id:string;label:string;hint?:string;error?:string;required?:boolean;children:React.ReactNode}){return <label htmlFor={id} className="person-field"><span>{label}{required&&<b aria-hidden="true"> *</b>}</span>{children}{hint&&!error&&<small>{hint}</small>}{error&&<small className="is-error" role="alert">{error}</small>}</label>}
function validate(form:FormState){const errors:Record<string,string>={};if(!form.names.given.trim())errors.given="Enter a given name.";if(!form.homeBranchId)errors.branch="Choose a home branch.";if(form.dateOfBirth&&!form.dateOfBirth.value)errors.dob="Enter the known date value.";if(form.address.line2&& !form.address.line1)errors.line1="Enter the main address line first.";for(const contact of form.contacts){if(!contact.value.trim())continue;if(contact.type==="email"){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.value.trim()))errors[`contact-${contact.id}`]="Enter a valid email address.";}else{const value=contact.value.replace(/[\s()-]/g,"");if(!/^(?:\+233|0)\d{9}$/.test(value))errors[`contact-${contact.id}`]="Use 0XXXXXXXXX or +233XXXXXXXXX.";}}return errors;}
function toPayload(form:FormState){return {homeBranchId:form.homeBranchId,names:form.names,photoAssetId:form.photoAssetId||undefined,dateOfBirth:form.dateOfBirth||undefined,gender:form.gender||undefined,contactPoints:form.contacts.filter(contact=>contact.value.trim()).map(({id:_,...contact})=>contact),addresses:form.address.line1?[{...form.address,primary:true}]:[],membershipStage:form.membershipStage,tags:form.tags,customFields:{},communicationPreferences:form.preferences,source:form.source};}
function fromPerson(person:MemberProfile["person"]):FormState{const contacts=(person.contactPoints||[]).map((contact,index)=>({id:`contact-${index}`,type:contact.type as ContactType,value:contact.value,primary:!!contact.primary}));return {...EMPTY,names:{given:person.names.given||"",middle:person.names.middle||"",family:person.names.family||"",preferred:person.names.preferred||""},photoAssetId:person.photoAssetId||"",photoPreviewUrl:person.photoUrl||"",dateOfBirth:person.dateOfBirth||null,gender:person.gender||"",homeBranchId:person.homeBranchId,membershipStage:person.membershipStage,contacts:contacts.length?contacts:EMPTY.contacts,address:person.addresses?.[0]?{line1:person.addresses[0].line1,line2:person.addresses[0].line2||"",city:person.addresses[0].city||"",region:person.addresses[0].region||"Greater Accra",country:person.addresses[0].country||"GH"}:EMPTY.address,tags:person.tags||[],preferences:{email:!!person.communicationPreferences?.email,sms:!!person.communicationPreferences?.sms,whatsapp:!!person.communicationPreferences?.whatsapp,phone:!!person.communicationPreferences?.phone},source:EMPTY.source};}
function hasMeaningfulDraft(form:FormState){return Boolean(form.names.given.trim()||form.names.middle.trim()||form.names.family.trim()||form.names.preferred.trim()||form.photoAssetId||form.photoPreviewUrl||form.dateOfBirth?.value||form.gender||form.contacts.some(contact=>contact.value.trim())||form.address.line1.trim()||form.address.line2.trim()||form.address.city.trim()||form.tags.length);}
