"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Card, EmptyState, ErrorBox, PageHeader } from "@/components/ui";
import { Select } from "@/components/ui/Select";
import { api, apiDownload, ApiError } from "@/lib/api";

type Campus = { branchId: string; name: string };
type Period = { id: string; name: string; code: string; startsAt: string; endsAt: string; status: string };
type FundRow = { fundId: string; fundCode: string; fundName: string; amountMinor: number; giftCount: number };
type TrendRow = { date: string; amountMinor: number; giftCount: number };
type DepositRow = { settlementId: string; reference: string; settledAt: string; state: string; grossAmountMinor: number; netAmountMinor: number; matchedGrossMinor: number; unexplainedVarianceMinor: number; unresolvedCount: number };
type PledgeRow = { fundId: string; fundName: string; pledgeCount: number; targetAmountMinor: number; fulfilledAmountMinor: number; remainingAmountMinor: number };
type Report = { meta: { metricVersion: string; asOf: string; sourceWatermark: string; timezone: string; branchId: string; periodId?: string; startsAt: string; endsAt: string; caveats: string[] }; totals: { netContributionMinor: number; contributionCount: number; adjustmentCount: number; anonymousCount: number; unresolvedCount: number; settlementGrossMinor: number; settlementNetMinor: number; unexplainedMinor: number; pledgeTargetMinor: number; pledgeFulfilledMinor: number }; fundMovement: FundRow[]; givingTrend: TrendRow[]; depositReconciliation: DepositRow[]; pledgeProgress: PledgeRow[] };
type ExportRun = { id: string; kind: string; status: string; fileName: string; artifactHash: string; rowCount: number; totalAmountMinor: number; createdAt: string; report: { meta: Report["meta"] } };
const rows = <T,>(value: unknown): T[] => Array.isArray(value) ? value as T[] : value && typeof value === "object" && Array.isArray((value as { items?: unknown[] }).items) ? (value as { items: T[] }).items : [];
const money = (minor = 0) => new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS", maximumFractionDigits: 0 }).format(minor / 100);
const date = (value: string) => new Date(value).toLocaleDateString("en-GH", { day: "numeric", month: "short", year: "numeric" });

export default function FinanceReportsPage() {
  const [campuses, setCampuses] = useState<Campus[]>([]), [periods, setPeriods] = useState<Period[]>([]), [branchId, setBranchId] = useState(""), [periodId, setPeriodId] = useState("");
  const [report, setReport] = useState<Report | null>(null), [exports, setExports] = useState<ExportRun[]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(""), [error, setError] = useState<string | null>(null), [notice, setNotice] = useState("");
  const loadFoundation = useCallback(async () => { setLoading(true); setError(null); try { const [campusData, periodData] = await Promise.all([api("/api/chms/v1/finance/campuses"), api("/api/chms/v1/finance/periods")]); const nextCampuses = rows<Campus>(campusData), nextPeriods = rows<Period>(periodData); setCampuses(nextCampuses); setPeriods(nextPeriods); setBranchId((current) => current || nextCampuses[0]?.branchId || ""); setPeriodId((current) => current || nextPeriods[0]?.id || ""); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Finance report controls could not be loaded."); } finally { setLoading(false); } }, []);
  const loadReport = useCallback(async () => { if (!branchId || !periodId) return; setLoading(true); setError(null); try { const [reportData, exportData] = await Promise.all([api<Report>(`/api/chms/v1/finance/reports/summary?branchId=${encodeURIComponent(branchId)}&periodId=${encodeURIComponent(periodId)}`), api(`/api/chms/v1/finance/export-runs?branchId=${encodeURIComponent(branchId)}`)]); setReport(reportData); setExports(rows<ExportRun>(exportData)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "The reconciled finance report could not be loaded."); } finally { setLoading(false); } }, [branchId, periodId]);
  useEffect(() => { void loadFoundation(); }, [loadFoundation]); useEffect(() => { void loadReport(); }, [loadReport, notice]);
  async function createExport(kind: "accounting-csv" | "audit-package") { if (!branchId || !periodId) return; setBusy(kind); setError(null); setNotice(""); try { const run = await api<ExportRun>("/api/chms/v1/finance/export-runs", { method: "POST", body: { kind, branchId, periodId } }); setNotice(`${kind === "accounting-csv" ? "Accounting CSV" : "Audit package"} generated with SHA-256 ${run.artifactHash.slice(0, 12)}…`); await apiDownload(`/api/chms/v1/finance/export-runs/${run.id}/download`, run.fileName); } catch (cause) { setError(cause instanceof ApiError && cause.status === 404 ? "Export requires explicit finance-export authority and a recent MFA confirmation. Sign in again with MFA, then retry this controlled action." : cause instanceof ApiError ? cause.message : "The finance export could not be generated."); } finally { setBusy(""); } }
  const maxTrend = Math.max(1, ...(report?.givingTrend.map((item) => Math.abs(item.amountMinor)) || [1]));
  const pledgePercent = report?.totals.pledgeTargetMinor ? Math.min(100, Math.round(report.totals.pledgeFulfilledMinor / report.totals.pledgeTargetMinor * 100)) : 0;
  const period = periods.find((item) => item.id === periodId);
  return <div><PageHeader title="Finance reports & exports" subtitle="Reconcile fund movement, giving trends, deposits and voluntary pledge progress to the same immutable source query before exporting."><div className="grid min-w-72 gap-3 sm:grid-cols-2"><label className="admin-field"><span>Branch</span><Select value={branchId} onChange={(event) => setBranchId(event.target.value)}>{campuses.map((item) => <option value={item.branchId} key={item.branchId}>{item.name}</option>)}</Select></label><label className="admin-field"><span>Fiscal period</span><Select value={periodId} onChange={(event) => setPeriodId(event.target.value)}>{periods.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.status}</option>)}</Select></label></div></PageHeader>
    {error && <ErrorBox message={error} onRetry={() => void loadReport()} />}{notice && <p role="status" className="mb-5 rounded-xl bg-emerald-500/10 px-4 py-3 text-sm font-semibold text-emerald-800">{notice}</p>}
    {!report && !loading ? <EmptyState title="No report is available" hint="Configure a branch and fiscal period before generating finance reporting." /> : report && <>
      <section className="grid gap-px overflow-hidden rounded-2xl border border-white/[.08] bg-white/[.08] text-white shadow-[0_24px_60px_rgba(16,25,19,.18)] sm:grid-cols-2 xl:grid-cols-4" style={{ backgroundColor: "var(--remi-green)" }}><HeroStat label="Net posted movement" value={money(report.totals.netContributionMinor)} /><HeroStat label="Posted ledger rows" value={String(report.totals.contributionCount).padStart(2, "0")} note={`${report.totals.adjustmentCount} adjustments`} /><HeroStat label="Settlement net" value={money(report.totals.settlementNetMinor)} note={`${money(report.totals.unexplainedMinor)} unexplained`} /><HeroStat label="Pledge progress" value={`${pledgePercent}%`} note={`${money(report.totals.pledgeFulfilledMinor)} fulfilled`} /></section>
      <section className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="overflow-hidden"><Panel title="Giving movement" note={`${date(report.meta.startsAt)} – ${date(report.meta.endsAt)}`} /><div className="grid min-h-64 grid-cols-[repeat(auto-fit,minmax(2.2rem,1fr))] items-end gap-2 p-6" aria-label="Daily posted giving chart">{report.givingTrend.map((item) => <div className="group flex h-full min-h-44 flex-col justify-end" key={item.date}><div title={`${date(item.date)} · ${money(item.amountMinor)} · ${item.giftCount} rows`} className={`min-h-1 rounded-t-md transition group-hover:opacity-75 ${item.amountMinor < 0 ? "bg-rose-400" : "bg-[var(--remi-gold)]"}`} style={{ height: `${Math.max(3, Math.abs(item.amountMinor) / maxTrend * 100)}%` }} /><span className="mt-2 truncate text-center font-mono text-[8px] text-[var(--remi-muted)]">{item.date.slice(5)}</span></div>)}{report.givingTrend.length === 0 && <div className="col-span-full self-center"><EmptyState dense title="No ledger movement in this period" hint="Posted gifts and adjustments will appear here." /></div>}</div></Card><Card className="overflow-hidden"><Panel title="Control health" note={period?.status || "period"} /><div className="grid grid-cols-2"><ControlMetric label="Anonymous rows" value={report.totals.anonymousCount} /><ControlMetric label="Unresolved donors" value={report.totals.unresolvedCount} /><ControlMetric label="Adjustments" value={report.totals.adjustmentCount} /><ControlMetric label="Unexplained" value={money(report.totals.unexplainedMinor)} /></div><div className="border-t border-black/[.045] p-5"><div className="flex justify-between text-xs"><b>Voluntary pledge fulfillment</b><span>{pledgePercent}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/[.06]"><i className="block h-full rounded-full bg-[var(--remi-gold)]" style={{ width: `${pledgePercent}%` }} /></div><p className="mt-3 text-xs leading-5 text-[var(--remi-muted)]">Pledges are intentions, not debt. These totals are excluded from retention scoring and member ranking.</p></div></Card></section>
      <section className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="overflow-hidden"><Panel title="Fund movement" note={`${report.fundMovement.length} designations`} /><div className="divide-y divide-black/[.045]">{report.fundMovement.map((item) => <article className="grid grid-cols-[1fr_auto] gap-4 p-5" key={item.fundId}><div><b className="text-sm">{item.fundName || item.fundId}</b><small className="mt-1 block font-mono text-[9px] uppercase text-[var(--remi-muted)]">{item.fundCode || "Unmapped fund"} · {item.giftCount} ledger rows</small></div><strong className="font-mono text-sm">{money(item.amountMinor)}</strong></article>)}{report.fundMovement.length === 0 && <div className="p-5"><EmptyState dense title="No fund movement" hint="There are no posted splits in this period." /></div>}</div></Card><Card className="overflow-hidden"><Panel title="Deposit reconciliation" note={`${report.depositReconciliation.length} evidence files`} /><div className="divide-y divide-black/[.045]">{report.depositReconciliation.map((item) => <article className="p-5" key={item.settlementId}><div className="flex flex-wrap justify-between gap-3"><span><b className="block text-sm">{item.reference}</b><small className="mt-1 block text-[var(--remi-muted)]">{date(item.settledAt)} · {item.state}</small></span><b className="font-mono text-sm">{money(item.netAmountMinor)}</b></div><div className="mt-3 grid grid-cols-3 gap-2 text-[10px]"><Mini label="Gross" value={money(item.grossAmountMinor)} /><Mini label="Matched" value={money(item.matchedGrossMinor)} /><Mini label="Unexplained" value={money(item.unexplainedVarianceMinor)} alert={item.unexplainedVarianceMinor !== 0} /></div></article>)}{report.depositReconciliation.length === 0 && <div className="p-5"><EmptyState dense title="No settlement evidence" hint="Imported processor, bank and deposit evidence will appear here." /></div>}</div></Card></section>
      <Card className="mt-5 overflow-hidden"><Panel title="Pledge progress by fund" note="Aggregate intention tracking" /><div className="divide-y divide-black/[.045]">{report.pledgeProgress.map((item) => { const percent = item.targetAmountMinor ? Math.min(100, Math.round(item.fulfilledAmountMinor / item.targetAmountMinor * 100)) : 0; return <article className="grid gap-4 p-5 md:grid-cols-[minmax(12rem,1fr)_2fr_auto] md:items-center" key={item.fundId}><div><b className="text-sm">{item.fundName || item.fundId}</b><small className="mt-1 block text-[var(--remi-muted)]">{item.pledgeCount} active or historical intentions</small></div><div><div className="h-2 overflow-hidden rounded-full bg-black/[.06]"><i className="block h-full rounded-full bg-[var(--remi-gold)]" style={{ width: `${percent}%` }} /></div><small className="mt-2 block text-[var(--remi-muted)]">{money(item.fulfilledAmountMinor)} of {money(item.targetAmountMinor)}</small></div><b className="font-mono text-sm">{percent}%</b></article>})}{report.pledgeProgress.length === 0 && <div className="p-5"><EmptyState dense title="No pledge activity" hint="Voluntary fund intentions will appear without individual rankings." /></div>}</div></Card>
      <section className="mt-6 grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card className="p-6"><span className="font-mono text-[10px] uppercase tracking-[.16em] text-[var(--remi-gold-deep)]">Controlled exports</span><h2 className="mt-2 text-xl font-bold">Generate a reconciled artifact</h2><p className="mt-2 text-xs leading-5 text-[var(--remi-muted)]">Export requires recent MFA. Every artifact stores this report snapshot, source watermark, SHA-256 hash, row count and total, then appends an immutable audit event.</p><div className="mt-5 grid gap-2"><button disabled={Boolean(busy)} onClick={() => void createExport("accounting-csv")} className="admin-primary-button">{busy === "accounting-csv" ? "Generating…" : "Generate accounting CSV"}</button><button disabled={Boolean(busy)} onClick={() => void createExport("audit-package")} className="admin-secondary-button">{busy === "audit-package" ? "Packaging…" : "Generate audit package (.zip)"}</button></div></Card><Card className="overflow-hidden"><Panel title="Export history" note={`${exports.length} immutable runs`} /><div className="divide-y divide-black/[.045]">{exports.map((item) => <article className="grid gap-3 p-5 sm:grid-cols-[1fr_auto] sm:items-center" key={item.id}><div><b className="block text-sm">{item.fileName}</b><small className="mt-1 block text-[var(--remi-muted)]">{new Date(item.createdAt).toLocaleString("en-GH")} · {item.rowCount} rows · {money(item.totalAmountMinor)}</small><code className="mt-2 block truncate font-mono text-[9px] text-[var(--remi-muted)]">SHA-256 {item.artifactHash}</code></div><button onClick={() => void apiDownload(`/api/chms/v1/finance/export-runs/${item.id}/download`, item.fileName)} className="admin-secondary-button !px-3 !py-2 text-xs">Download</button></article>)}{exports.length === 0 && <div className="p-5"><EmptyState dense title="No exports generated" hint="The first approved artifact will remain available here." /></div>}</div></Card></section>
      <footer className="mt-6 rounded-xl border border-black/[.05] bg-[var(--remi-surface)] p-4 text-xs leading-5 text-[var(--remi-muted)]"><b className="text-[var(--remi-ink)]">Metric {report.meta.metricVersion}</b> · As of {new Date(report.meta.asOf).toLocaleString("en-GH")} · {report.meta.timezone}<br /><span className="font-mono text-[9px]">Source watermark {report.meta.sourceWatermark}</span><ul className="mt-2 list-disc pl-4">{report.meta.caveats.map((item) => <li key={item}>{item}</li>)}</ul></footer>
    </>}
  </div>;
}
function HeroStat({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="bg-white/[.035] p-5"><b className="block font-mono text-xl tabular-nums">{value}</b><span className="mt-2 block text-[9px] font-bold uppercase tracking-[.15em] text-white/40">{label}</span>{note && <small className="mt-1 block text-white/30">{note}</small>}</div>; }
function Panel({ title, note }: { title: string; note: string }) { return <header className="flex items-end justify-between gap-4 border-b border-black/[.045] p-5"><h2 className="font-bold">{title}</h2><small className="text-right text-[var(--remi-muted)]">{note}</small></header>; }
function ControlMetric({ label, value }: { label: string; value: string | number }) { return <div className="border-b border-black/[.045] p-5 even:border-l"><b className="block font-mono text-lg">{value}</b><span className="mt-1 block text-[9px] uppercase tracking-wider text-[var(--remi-muted)]">{label}</span></div>; }
function Mini({ label, value, alert = false }: { label: string; value: string; alert?: boolean }) { return <span className={`rounded-lg p-2 ${alert ? "bg-rose-500/10 text-rose-700" : "bg-black/[.025]"}`}><small className="block text-[8px] uppercase text-[var(--remi-muted)]">{label}</small><b className="mt-1 block font-mono">{value}</b></span>; }
